USE His3000
GO

ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_CL_ESTABLE        INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_CL_INESTABLE      INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_CL_FALLECIDO      INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_CL_MOTIVO         VARCHAR (500) NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_ACT_TRA           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_VIO_ARM           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_INT_ALC           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_CAIDA             INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_VIO_PUN           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_INT_ALI           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_QUEMADURA         INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_VIO_RINA          INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_INT_DRO           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_MORDEDURA         INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_VIO_FAM           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_INH_GAS           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_AHOGAMIENTO       INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_PRE_FIS           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_OTR_INT           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_CUE_EXT           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_PRE_PSI           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_PICADURA          INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_APLASTAMIENTO     INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_PRE_SEX           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_ENVENENAMIENTO    INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_OTR_ACC           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_NOTIFICACION      INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_ANAFILAXIA        INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_LLE_CAP           VARCHAR (6) NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_SIN_VIT           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_PERIMETRO         VARCHAR (6) NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_GRU_PRIO          INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_PRIORITARIO       VARCHAR (50) NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_HOSPITALIZACION   INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_REF_INV           INT NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_OBS_EGR           VARCHAR (500) NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_DERIVACION        INT NULL;
alter table HC_EMERGENCIA_FORM ALTER COLUMN EMER_DIRECCION_EVENTO VARCHAR(500)
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_OBS_EXA_FIS          VARCHAR (1000) NULL;
ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_ALT_DEF        INT NULL;
alter table HC_EMERGENCIA_FORM ALTER COLUMN EMER_CAUSA_MUERTE VARCHAR(500);
UPDATE HC_CATALOGOS SET HCC_NOMBRE='HOSPITALIZACIÓN' WHERE HCC_CODIGO=879;
ALTER TABLE HC_EMERGENCIA_FORM  alter column	EMER_OBS_EXA_FIS          VARCHAR (1000) NULL;
update HC_CATALOGOS set HCC_NOMBRE='TRAUMATÓGICO' where HCC_CODIGO=828;
update HC_CATALOGOS set HCC_NOMBRE='FARMACOLÓGICO' where HCC_CODIGO=830;


ALTER TABLE HC_EMERGENCIA_FORM  ADD	EMER_SCORE        INT NULL;


-----------------------------------
alter table HC_EMERGENCIA_FORM_TRATAMIENTO add DOSIS VARCHAR (50);
alter table HC_EMERGENCIA_FORM_TRATAMIENTO add VIA VARCHAR (50);
alter table HC_EMERGENCIA_FORM_TRATAMIENTO add DIAS VARCHAR (50);
-------------------------
INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (893, 48, 'PIEL-FANERAS', 1)
GO

INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (894, 48, 'OJOS', 1)
GO

INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (895, 48, 'OROFARINGE', 1)
GO

INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (896, 48, 'OIDOS', 1)
GO

INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (897, 48, 'BOCA', 1)
GO

INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (898, 48, 'AXILAS MAMAS', 1)
GO

INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (899, 48, 'INGLE PERINE', 1)
GO

INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (900, 48, 'MIEMBROS SUPERIORES', 1)
GO

INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (901, 48, 'MIEMBROS INFERIORES', 1)
GO

INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (902, 48, 'NARIZ', 1)
GO

INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (903, 47, 'HABITOS', 1)
GO

INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (904, 47, 'FAMILIARES', 1)
GO

INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO) VALUES (905, 47, 'PEDIATRICOS', 1)
GO

ALTER TABLE FORMULARIOS_HCU ADD fecha DATE;
UPDATE FORMULARIOS_HCU SET fecha='14/03/2024' WHERE FH_codigo=7;