--Anamnesis 2024/03/06 Andres Cabrera

--Añadir campos nuevos a Antecedentes de la Mujer
ALTER TABLE HC_ANAMNESIS_ANTEC_MUJER
ADD AMU_SCORE_MAMA INT, AMU_EDAD_VIDA_SEXUAL INT, 
AMU_FECHA_COLPOSCOPIA date,AMU_FECHA_MAMOGRAFIA date, AMU_CICLOS_DETALLE char(1);

--Añadir campos nuevos a ANAMNESIS
ALTER TABLE HC_ANAMNESIS
ADD ANE_OTROS_SIGNOS text, ANE_FECHA_ULT_ECO_PROSTATICO DATE,
    ANE_FECHA_ULT_ANTIGENO_PROSTATICO DATE, ANE_ANALISIS text;

--Actualizar el parametro para mostrar los formularios nuevos o antiguos
UPDATE FORMULARIOS_HCU
SET fecha = '2024-04-08'
WHERE FH_CODIGO = 3;

UPDATE HC_CATALOGOS
SET HCC_NOMBRE = 'HIPERTENSIÓN'
WHERE HCC_CODIGO = 28;

UPDATE HC_CATALOGOS
SET HCC_NOMBRE = 'MALFORMACIÓN'
WHERE HCC_CODIGO = 33;

UPDATE HC_CATALOGOS
SET HCC_NOMBRE = 'OROFARINGE'
WHERE HCC_CODIGO = 51;

UPDATE HC_CATALOGOS
SET HCC_NOMBRE = 'HÁBITOS'
WHERE HCC_CODIGO = 22;

UPDATE HC_CATALOGOS
SET HCC_NOMBRE = 'CARDIOPATÍA'
WHERE HCC_CODIGO = 25;

UPDATE HC_CATALOGOS
SET HCC_NOMBRE = 'ENFERMEDAD MENTAL'
WHERE HCC_CODIGO = 31;

UPDATE HC_CATALOGOS
SET HCC_NOMBRE = 'RELIGIÓN'
WHERE HCC_CODIGO = 23;

UPDATE HC_CATALOGOS
SET HCC_NOMBRE = 'ÓRGANOS DE LOS SENTIDOS.'
WHERE HCC_CODIGO = 35;

UPDATE HC_CATALOGOS
SET HCC_NOMBRE = 'RESPIRATORIO.'
WHERE HCC_CODIGO = 917;

UPDATE HC_CATALOGOS
SET HCC_NOMBRE = 'DIGESTIVO.'
WHERE HCC_CODIGO = 38;

UPDATE HC_CATALOGOS
SET HCC_NOMBRE = 'ENDÓCRINO.'
WHERE HCC_CODIGO = 42;

--Registros para el nuevo Anamneis 
INSERT INTO HC_CATALOGOS (HCC_CODIGO, HCT_TIPO, HCC_NOMBRE, HCC_ESTADO)
VALUES
    (906, 2, 'ALERGIA A MEDICAMENTOS', 1),
    (907, 2, 'OTRAS ALERGIAS', 1),
    (908, 2, 'PATOLOGIA CLÍNICA', 1),
    (909, 2, 'MEDICACION HABITUAL', 1),
    (910, 2, 'QUIRÚRGICOS', 1),
    (911, 2, 'CONDICIÓN SOCIOECONÓMICA', 1),
    (912, 2, 'DISCAPACIDAD', 1),
    (913, 2, 'TIPIFICACIÓN SANGUÍNEA', 1),
    (914, 3, 'ENDOCRINO METABÓLICO', 1),
    (915, 4, 'PIEL-ANEXOS', 1),
	(926, 4, 'GÉNITO-URINARIO', 1),
	(916, 5, 'ÓRGANOS DE LOS SENTIDOS', 1),
	(917, 5, 'RESPIRATORIO', 1),
	(918, 5, 'CARDIO - VASCULAR', 1),
	(919, 5, 'DIGESTIVO', 1),
	(920, 5, 'GENITAL', 1),
	(921, 5, 'URINARIO', 1),
	(922, 5, 'MÚSCULO - ESQUELÉTICO', 1),
	(923, 5, 'ENDÓCRINO', 1),
	(924, 5, 'HEMO - LINFÁTICO', 1),
	(925, 5, 'NEUROLÓGICO', 1);
